### ISSUE TITLE
Turn-based problem

### ISSUE THREAD

**Issue by HerryZheng8** [ScaredKurufinve/Way-of-the-shield#8]
When I use turn-based games，Combat will get stuck，Switch to the instant system and then switch back to the combined system，For the game to work

**Comment by ScaredKurufinve** [comment]
Do you have this problem only with my mod? I know such problem was present in the base game too. If it happens only with my mod, are there any common factors to its occurence? For example, only when you activate certain abilities or something similar? I am unable to reproduce this problem myself.

**Comment by HerryZheng8** [comment]
I'm sure, because I haven't had this problem since I uninstalled this MOD

**Comment by HerryZheng8** [comment]
I'm not sure exactly how it happened, but maybe I changed Seelah's class to divine guardian

**Comment by ScaredKurufinve** [comment]
I am terribly sorry, but I am unable to find any evidences of such a bug. I asked people on Discord who also use this mod, and they also say they never encountered anything like this. You may still try to take the `Way of the Shield.dll` file from the mod's Debug folder, put it inside the Assemblies folder instead of the existing one and (after enabling the Debug option in the mod settings) play until you encounter the bug  to generate the detailed log which I can analyze. But I doubt I will be able to find anything to detect the issue.

**Comment by HerryZheng8** [comment]
OK,I will try.

**Comment by Bigeam** [comment]
I also encountered this bug. Occasionally appears while under the influence of the HolyShield

**Comment by ScaredKurufinve** [comment]
> I also encountered this bug. Occasionally appears while under the influence of the HolyShield

Hm 🤔 I will try to reproduce. But it kinda sounds like some stupid base game problem with area effects.

**Comment by KTVSUN** [comment]
I have the same issue, only with my 2 mounted characters.

**Comment by ScaredKurufinve** [comment]
> I have the same issue, only with my 2 mounted characters. Edit: problem disappears when i desactivate the option for "allow couching spears".

How curious. I can't reproduce that. Do your mounted characters actually use couched spears or only the setting is active and they use some other weaponry?

**Comment by KTVSUN** [comment]
It started doing it again and i realized by default the option to use shield bash is active, none of these characters had shields equiped so i deactivated it and the combat went on without problem. Cant test more today will do tomorrow.

**Comment by ScaredKurufinve** [comment]
Oh, that's the PredictionPanelFiveFeetActionVM problem. Hm. I don't think we ever figured out what causes it, but your info may help.

**Comment by ScaredKurufinve** [comment]
@KTVSUN Hm, may I ask you to completely delete the mod, make sure it's not in the game folder or in the UMM folder or in the `AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous\Modifications` folder (or whereever your OS places it) and then reinstall? The log contains an error about a badly configured blueprint, and I'm fairly sure I fixed the last one in version 2.0.7
Unfortunately, due to a bug in OwlCode, the error message can not display correctly which exactly buff that it. If a clean re-install of the mod won't help, substitute the game dll with the file from attachment as seen on the screenshot and send me new Game Log again (you may want to back up the original in case something goes wrong, but it shouldn't).
![2](https://github.com/ScaredKurufinve/Way-of-the-shield/assets/126824833/2972d743-aa34-43c5-8ca9-316206918dea)
[Assembly-CSharp.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11610159/Assembly-CSharp.zip)

**Comment by KTVSUN** [comment]
Good morning, removed mod from umm folder and game folder, downloaded the latest version again and still have the problem. Got to work a bit then will do the dll swap. In meantime logs until the moment seelah stopped responding.
[GameLog.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11614283/GameLog.zip)
[Player.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11614287/Player.zip)

**Comment by KTVSUN** [comment]
Bqcked up my dll, uploaded then one you sent.
Ran the game again at the same fight and this time instead of blocking when it s  seelah s turn it just skipped her everytime. I checked and she had no debuff that would justify this. Here are the logs
[Player.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11615078/Player.zip)
[GameLog.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11615082/GameLog.zip)

**Comment by KTVSUN** [comment]
I also noticed my log is huge when running your mod and i believe it s because it s spammed with :
[479.9473 - Default]: Exception occured!
Kingmaker.GameModes.GameMode.Tick() (at :0)
Kingmaker.Game.Tick() (at :0)
Kingmaker.Runner.Update() (at :0)

[479.9482 - Default]: Object reference not set to an instance of an object
  at Kingmaker.View.MapObjects.AreaEffectView.Contains (Kingmaker.EntitySystem.Entities.UnitEntityData unit) [0x00089] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.ShouldUnitBeInside (Kingmaker.EntitySystem.Entities.UnitEntityData unit) [0x000fb] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.UpdateUnit (Kingmaker.EntitySystem.Entities.UnitEntityData unit) [0x00018] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.UpdateUnits () [0x00102] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.UpdateViewAndUnits () [0x0009c] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.HandleEnd () [0x00000] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.EntitySystem.Entities.AreaEffectEntityData.Tick () [0x0000e] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.Controllers.AreaEffectsController.EffectTick (Kingmaker.EntitySystem.Entities.AreaEffectEntityData areaEffect, Kingmaker.Controllers.Optimization.FrameContext context) [0x00000] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.Controllers.AreaEffectsController+<>c.<Tick>b__4_0 (Kingmaker.EntitySystem.Entities.AreaEffectEntityData data, Kingmaker.Controllers.Optimization.FrameContext context) [0x00000] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.Controllers.Optimization.TickProlongationEntityPool`2[T,TContext].Tick (System.Action`2[T1,T2] tickAction, TContext frameContext) [0x00057] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.Controllers.Optimization.MixedTickProlongationEntityPool`2[T,TContext].Tick (System.Action`2[T1,T2] tickAction, TContext frameContext) [0x00031] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.Controllers.AreaEffectsController.Tick () [0x00019] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

  at Kingmaker.GameModes.GameMode.Tick () [0x0002f] in <9fbdaaba94e842ff9fe97bf4617a0789>:0 

I removed your mod, loaded my last save before i installed it and checked the log after 1 fight. I dont have any instance of this spam while there are more than 13000 in a few minutes of play with it installed.

Hope it helps

**Comment by KTVSUN** [comment]
Hello, i removed it for now and rolled back to a previous save. Will try to reinstall and test ina  dungeon without golems

**Comment by ScaredKurufinve** [comment]
@KTVSUN after giving a second look to the log, I noticed this error which is probably the one which was likely the reason for the interface crash:
`[481.7680 - Actions]: Exception in game logic: .Conditional#Nameless component of type Kingmaker.Designers.EventConditionActionSystem.Actions.Conditional from the blueprint NULL OWNER BLUEPRINT [Object reference not set to an instance of an object] ()`
And there are two problems with it:
1) I don't understand why the problem still persist even thought the error is somewhat handled
2) I don't know what causes it - as you can see from the message, it's caused by a nameless Conditional element coming from a null blueprint. I don't know who this can be theoretically possible. Additionally, the reason why the error happens in the first place is because this Conditional is lacking the IfTrue branch and I double-checked yesterday, but all of my Conditionals do have it. Without any additional hints, I can't even start guessing how to fix it.

**Comment by Bakaten** [comment]
Hi Kuru,
I'm currently playing on 2.0.8 and so far is fine, but will update you in the future if the problem reoccurs. 
Just to add that based on my past playthrough, it only happened specifically on Seelah's horse acquired through divine bond. 
It is the horse's turn that get stucked (both normal and black horses), mounted as well as unmounted (in the case of mounted, Seelah will also get stucked). All other companions' pet ( in my case they are dogs) are fine. Haven't tried with horses or any other animals on other companions' though. 
Hope this can help narrow down the source of the problem.
Cheers.

**Comment by ScaredKurufinve** [comment]
@Bakaten Thank you for the info! Did your horse happen to have any teamwork feat when the problem was happening? I'm thinking if maybe there's a teamwork feat broken and the bug happens only when the character and the pet are not close enough for it to activate. That being said, I'm still unable to reproduce, but very grateful to you for taking the time to report this.

**Comment by KTVSUN** [comment]
Traveling so answering through email.
My horses all have outflank.
Next week my wife is traveling to Europe soooo free time to play. I'll
see what I encounter. Hopefully nothing 😁

**Comment by Bakaten** [comment]
> @Bakaten Thank you for the info! Did your horse happen to have any teamwork feat when the problem was happening? I'm thinking if maybe there's a teamwork feat broken and the bug happens only when the character and the pet are not close enough for it to activate. That being said, I'm still unable to reproduce, but very grateful to you for taking the time to report a lot of valuable info.

Hi Kuru, nope, my horse only has crane style (and all it's prereqs) and fighting devensively. But I think mounting the horse is as close enough as it is :P, but the bug still happened. But so far on 2.0.9, blasting through chapter one without any problems.

Cheers
